---
title: "GO term analysis. Developmental Atlas"
output: html_notebook
---

# Packages

```{r}
library("EnsDb.Hsapiens.v86")
library(biomaRt)
library(ggplot2)
library(org.Hs.eg.db)
library(GO.db)
library(stringr)
library(clusterProfiler)
library(AnnotationDbi)
library(enrichplot)
library(ggnewscale)
library(xlsx)
library(stringr)

columns(org.Hs.eg.db)

```


# IO

```{r}
#in_path <- "~/Desktop/Github/Immune_Adaptation_Atlas_2023/immune_gene_list/cell_lines_outputs/"
in_path <- "~/Desktop/Github/Immune_Adaptation_Atlas_2023/results_2024/cases/development/"
```


## Goterm enrichment function

```{r}
GO_cell_types_ALL <- function( all_cells, sig_cells) {
  cont = 0
  out_path <- "./Developmental/plots/"
  for (g in all_cells)
  {
    #g = "Bcells_ABCs"
    print(g)
    de <- read.table(file = paste0(in_path,g,"_case.txt" ),
                     header = F)[,1]
    # DE genes (500 at most)
    if (length(de)>500) {de <- de[1:500]}
    #de <- compartment_df[, g]
    #de <- de[de != ""]
    # RUN GOterm analysis
    GO_res <- enrichGO(gene = de, 
                       OrgDb = "org.Hs.eg.db", 
                       keyType = "ENSEMBL", ont = "BP")
    df <- as.data.frame(GO_res)
    if (dim(df)[1] > 0)
      {
      cont = cont + 1
     # GO_resX <- setReadable(GO_res, 'org.Hs.eg.db', 'ENSEMBL')
      GO_res2 <- pairwise_termsim(GO_res)
      # export as excel
      file <- paste0("./Developmental/Developmental_GO_term_enrichment_BP.xlsx")
      if (cont == 1) {write.xlsx(df, file, sheetName=g, col.names=TRUE,
                          row.names=FALSE, append=FALSE)
        } else {write.xlsx(df, file, sheetName=g, col.names=TRUE,
                          row.names=FALSE, append=TRUE) }
      if (g %in% sig_cells) {
        # plot image and export
       # p1 <- treeplot(GO_res2, showCategory = 30, offset = 2)
        p1 <- treeplot(GO_res2, offset = 4,showCategory = 30, fontsize = 3, nWords = 4)
        png(filename = paste0(out_path, g, ".png"), res = 300, units = "in", 
            height = 9,  width = 12 )
        plot(p1)
        dev.off()      
      }
    }
  }
}

```





## ALL cells


```{r}
all_files <- list.files(path = in_path)
#Tcells_files <- all_files[str_detect(string = all_files, pattern = "Tcells")]
all_files <- all_files[str_detect(string = all_files, pattern = "case.txt")]

All_CT <- vector()
for (i in 1:length(all_files))
{
#  i <- 1
  x <- str_remove(string = all_files[i], pattern = "_case.txt")
  All_CT <- c(All_CT, x)
}

```

```{r}
all_cells <- All_CT
sig_cells <-  c(
  # progenitors
  "HSC_progenitors_CMP", "HSC_progenitors_EARLY_MK", "HSC_progenitors_GMP",
  "HSC_progenitors_HSC_MPP", "HSC_progenitors_LMPP_MLP", "HSC_progenitors_MEMP",
  "HSC_progenitors_PRE_PRO_B", "HSC_progenitors_PROMONOCYTE",
  # Lymphoid
  "Lymphoid_ALL_B1",  "Lymphoid_ALL_DPP_T", "Lymphoid_ALL_ILC3",
  "Lymphoid_ALL_IMMATURE_B", "Lymphoid_ALL_LATE_PRO_B",
  "Lymphoid_ALL_MATURE_B", "Lymphoid_ALL_PRE_PRO_B", 
  "Lymphoid_ALL_TREG", "Lymphoid_ALL_TYPE_1_INNATE_T", 
  # MegaK
  "MegaK_Ery_EARLY_MK", "MegaK_Ery_MEP",
  # Myeloid
  "Myeloid_ALL_MACROPHAGE_LYVE1_HIGH", "Myeloid_ALL_MAST_CELL", "Myeloid_ALL_PROMONOCYTE")

GO_cell_types_ALL(all_cells = all_cells, sig_cells = sig_cells)


```


